NumPy is Linear Algebra Library for Python

NumPy is also incredibly fast, as it has bindings to C libraries

# Numpy Array

In [1]:
import numpy as np

In [3]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
ml = [[1,2,3], [4,5,6],[7,8,9]]

In [6]:
np.array(ml)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [9]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
np.linspace(0,5,50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.random.rand(5)

array([0.32345149, 0.91730227, 0.83444622, 0.32329375, 0.77635897])

In [21]:
np.random.rand(5,5)

array([[0.38202243, 0.95464413, 0.3397625 , 0.97877591, 0.36874788],
       [0.14383193, 0.193138  , 0.10416528, 0.58099693, 0.01934079],
       [0.21834014, 0.03876325, 0.59255628, 0.74348848, 0.10022653],
       [0.2074723 , 0.74879794, 0.39965414, 0.95174164, 0.14303827],
       [0.93498616, 0.87803159, 0.81962008, 0.00814938, 0.76940937]])

In [22]:
np.random.randn(2)

array([1.84416816, 0.50828979])

In [23]:
np.random.randn(2,2)

array([[ 0.09631326,  0.10657219],
       [-1.03129465,  1.21981604]])

In [24]:
np.random.rand(2,1)

array([[0.96094493],
       [0.56782749]])

In [25]:
np.random.rand(1,5)

array([[0.72592503, 0.20039703, 0.45259257, 0.81377838, 0.36079182]])

In [28]:
np.random.randint(1,100)

82

In [29]:
np.random.randint(1,100,13)

array([47, 88, 99, 52,  2, 12, 10, 61, 65, 16, 66, 16, 88])

In [30]:
a1 = np.arange(25)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
a3 = np.random.randint(0,50,10)
a3

array([35, 16, 39, 30,  8, 27, 24, 38, 21,  8])

In [33]:
a1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
a1.max()

24

In [36]:
a3.argmax()

2

In [37]:
a3.argmin()

4

In [38]:
a1.shape

(25,)

In [43]:
a2 = np.array(([1,2,3], [4,5,6]))
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
a2.shape

(2, 3)

In [47]:
a22 = a2.reshape(3,2)
a22

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
a22.shape

(3, 2)

In [49]:
a22.dtype

dtype('int32')

In [51]:
np.random.randint(3,12)

7